# Generated by Django 3.2.9 on 2021-11-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20211109_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTs', models.DateTimeField(auto_now_add=True)),
                ('updatedTs', models.DateTimeField(auto_now=True)),
                ('photoUri', models.URLField()),
                ('result', models.BooleanField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('modelFeedback', models.BooleanField()),
                ('modelVersion', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.patient')),
            ],
        ),
    ]
