# Generated by Django 3.2.9 on 2021-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='modelFeedback',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.BooleanField(null=True),
        ),
    ]
