# Generated by Django 3.2.9 on 2021-12-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_doctor'),
        ('detection', '0002_auto_20211118_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.doctor'),
        ),
    ]
