# Generated by Django 3.2.9 on 2021-12-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_record_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='annotationUri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='photoUri',
            field=models.URLField(null=True),
        ),
    ]
