# Generated by Django 3.2.9 on 2022-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_auto_20211228_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTs', models.DateTimeField(auto_now_add=True)),
                ('updatedTs', models.DateTimeField(auto_now=True)),
                ('model_id', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
