# Generated by Django 3.2.9 on 2022-02-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
