# Generated by Django 3.2.9 on 2022-02-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_alter_model_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='url',
        ),
    ]
