# Generated by Django 3.2.9 on 2023-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_remove_model_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='normalCount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='roundedRatio',
            field=models.FloatField(null=True),
        ),
    ]
