# Generated by Django 3.2.9 on 2023-06-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_auto_20230604_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='abnormalCount',
            field=models.FloatField(null=True),
        ),
    ]
