# Generated by Django 3.2.9 on 2021-12-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_alter_doctor_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTs', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.doctor')),
                ('patient', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.patient')),
            ],
        ),
    ]
