# Generated by Django 3.2.9 on 2021-11-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_auto_20211109_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('isVerified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
