# Generated by Django 3.2.9 on 2023-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_doctor_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='isVerified',
            field=models.BooleanField(default=True),
        ),
    ]
