# Generated by Django 3.2.9 on 2021-12-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTs', models.DateTimeField(auto_now_add=True)),
                ('updatedTs', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('doctor', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.doctor')),
                ('patient', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.patient')),
            ],
        ),
    ]
