# Generated by Django 3.2.9 on 2021-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
