# Generated by Django 3.2.9 on 2022-01-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_auto_20211228_2037'),
        ('request', '0002_request_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='detection.record'),
        ),
    ]
